#cloud-config

runcmd:
  - export HOME=/root
  - export WORKDIR="${HOME}/securedrop"
  - sudo apt-get update

  # --- SECUREDROP PREREQUISITES ---
  #
  # For the sake of easy cross-referencing, commands here are replicated as
  # faithfully as possible from the SecureDrop documentation as cited, even
  # when it would be easier to split them over multiline YAML strings, when
  # their "sudo" prefixes are no-ops under cloud-init, etc.

  # https://docs.securedrop.org/en/stable/development/setup_development.html#ubuntu-or-debian-gnu-linux
  # https://docs.docker.com/engine/install/debian/
  - sudo apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release

  - curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

  - echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

  - sudo apt-get update
  - sudo apt-get install -y docker-ce docker-ce-cli containerd.io

  # https://docs.securedrop.org/en/stable/development/setup_development.html
  - sudo apt-get install -y build-essential libssl-dev libffi-dev python3-dev dpkg-dev git linux-headers-$(uname -r)

  - sudo apt-get install -y python3-pip
  - python3 -m pip install --upgrade pip virtualenv

    # https://docs.securedrop.org/en/stable/development/virtual_environments.html#debian-stable-setup
  - sudo apt-get install -y vagrant libvirt-daemon-system qemu-kvm virt-manager
  - sudo apt-get install -y ansible rsync
  - apt-get remove -y vagrant-libvirt  # so that we can then...
  - vagrant plugin install vagrant-libvirt
  - vagrant plugin install vagrant-mutate

  - sudo rmmod kvm_intel
  - sudo rmmod kvm
  - sudo modprobe kvm
  - sudo modprobe kvm_intel

  - echo 'export VAGRANT_DEFAULT_PROVIDER=libvirt' >> ~/.bashrc
  - export VAGRANT_DEFAULT_PROVIDER=libvirt

  - vagrant box add --provider virtualbox bento/ubuntu-20.04
  - vagrant mutate bento/ubuntu-20.04 libvirt

  # -- SECUREDROP WORKSPACE ---
  - git clone https://github.com/freedomofpress/securedrop.git "$WORKDIR"

  - apt-get install -y enchant
  - apt-get install -y rustc
  - python3 -m pip install --ignore-installed --no-deps --require-hashes -r "${WORKDIR}/securedrop/requirements/python3/develop-requirements.txt"

